version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/lambda-words-types
      - .:/lambda-words-types/node_modules
    ports:
      - "3000:3000"